#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    ar.sort()
    sock=0
    #print(ar)
    for i in range (0,n-1,2):
        if (ar[i]==ar[i+1]):
            sock=sock+1
        else:
            i=i-1
    return (sock)
   # print(sock)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()

